### ISSUE TITLE
Using an absolute path for Log4jConfigFile property does not work on Windows

### ISSUE THREAD

**Issue by nieder-github** [ot4i/node-for-log4j#10]
Setting e.g. C:/temp/brokerlog.xml or C:\temp\brokerlog.xml as Log4jConfigFile will not work.

**Comment by nieder-github** [comment]
You need to configure the path with leading "/", e.g. /C:/temp/brokerlog.xml.

**Comment by vietph83** [comment]
I tested this on Windows and it worked. I think the leading "/" makes the path looks like on linux :)
Thanks for figuring that out.
