### ISSUE TITLE
Logs are not writing after upgrading Log4j Jars 2.17

### ISSUE THREAD

**Issue by cah-basha-boddu** [ot4i/node-for-log4j#2]
We tried to remediate the log4j 1.2 version by replacing the older jars with the new ones. We had

Log4jLoggingNode_v1.2.2.jar,
evd.jar,
jakarta-oro-2.0.4.jar,
log.jar and
log4j-1.2.8.jar

earlier, we replaced few jars and kept it as

log4j-1.2-api-2.17.2.jar
log4j-api-2.17.2.jar

log4j-core-2.17.2.jar

--------------------------------

Log4jLoggingNode_v1.2.2.jar,
evd.jar,
jakarta-oro-2.0.4.jar,
log.jar

**Comment by nieder-github** [comment]
Is there output in STDERR ?
Have you changed your log4j config to the new v2 syntax ?

**Comment by nieder-github** [comment]
please install the new par file as described in the User's guide.
Log4jLoggingNode_v1.x will not work with log4j v2, even if you provide the log4j-1.2-api-2.x.x.jar !!

**Comment by nieder-github** [comment]
Alternatetively you follow the workaround described here: [https://github.com/ot4i/node-for-log4j/issues/3](https://github.com/ot4i/node-for-log4j/issues/3)

**Comment by cah-basha-boddu** [comment]
#please install the new par file as described in the User's guide.
#Log4jLoggingNode_v1.x will not work with log4j v2, even if you provide the log4j-1.2-api-2.x.x.jar !!

Please provide the location from where we get it. I didn't find any users guide.

**Comment by nieder-github** [comment]
https://github.com/ot4i/node-for-log4j
-> iam3.pdf
