### ISSUE TITLE
Classloading issue when using node for log4j ESQL features

### ISSUE THREAD

**Issue by nieder-github** [ot4i/node-for-log4j#4]
Trying to deploy an ESQL with log4j code fails:

![image](https://user-images.githubusercontent.com/71630570/177331228-68a22812-241a-4481-a0ea-ce1ee6bf6641.png)

**Comment by nieder-github** [comment]
Follow the workaround described here: https://github.com/ot4i/node-for-log4j/issues/3
And put the jar files in the shared-classes folder.

**Comment by vietph83** [comment]
Hi nieder-github

I tried the following and it worked fine

1. Uncompress the par file Log4jLoggingNode_v2.0.1.par and copy all jar files to the shared-classes folder

2. jar everything in the classes folder (com and META-INF) as Log4jLoggingNode_v2.0.1.jar and copy it to the shared-classes folder

=> In the shared-classes folder I have the files below

jakarta-oro-2.0.8.jar
log4j-api-2.17.1.jar
log4j-core-2.17.1.jar
Log4jLoggingNode_v2.0.1.jar

=> Stop then start the integration node

Note: 
+ On Windows, for the integration node, the shared-classes folder is C:\ProgramData\IBM\MQSI\shared-classes)
+ For the standalone integration server (not managed by an integration node), we may need to create the directory shared-classes manually in the server work directory, then copy all the jar files here and stop/start the server.

=> I have no issue deploying the bar file using node-for-log4j functions in ESQL code as desribed in the iam3_v2.0.2.pdf

Thank you!

**Comment by nieder-github** [comment]
solved with version 2.1.0:
define a pluginFolder as policy ( ACE ) or Configurable Service ( IIB ) for your extensions
