### ISSUE TITLE
java.lang.NullPointerException when using ACE 12.0.6.0 and DEBUG log level 

### ISSUE THREAD

**Issue by ChrWeissDe** [ot4i/node-for-log4j#5]
Hi Mathias, 

As discussed: 
When using the log4jnode with the loglevel "DEBUG" in combination with ACE 12.0.6.0 I receive the error below.  
All other levels are working fine. 

== Error 
Exception. BIP2230E ...... 
.... BIP4395E: Java exception: 'java.lang.NullPointerException'; thrown from class name: 'com.ibm.broker.IAM3.Log4jNode', method name: 'evaluate', file: 'Log4jNode.java', line: '119' .... 

The error might be cause that the behaviour in ACE has changed and that the DEFAULT entry requires a dedicated "value attribute" (seen when we went together trough the source code). 

== Workaround: 
- not to use the DEBUG level in the log4jnode at the moment 
- will crosscheck if DEBUG can be used in the ESQL logging

**Comment by nieder-github** [comment]
Fixed with Release 2.0.1.
Only the server par-file must be replaced. There is no change in the toolkit.

**Comment by ChrWeissDe** [comment]
@nieder-github 
As discussed - the debug logging is now working. 
Thanks for the fix! 

Short summary of the required steps / my current setup: 
1.) Cleanup of the following folders - remove of all IAM related files (par, jars, log4j2 configs etc.)
<MQSI\shared-classes> - e.g.  C:\ProgramData\IBM\MQSI\shared-classes
<ACE-INSTALL\server\classes> -e.g. C:\Program Files\IBM\ACE\12.0.6.0\server\classes
shared-classes Verzeichnis vom Integration Server
2.) Repacking of Log4jLoggingNode_v2.0.1.par --> to Log4jLoggingNode_v2.0.1.jar (see https://github.com/ot4i/node-for-log4j/issues/3)
3.) Copy of the following files to MQSI\shared-classes: 
jakarta-oro-2.0.8.jar
log4j-api-2.17.1.jar
log4j-core-2.17.1.jar
Log4jLoggingNode_v2.0.1.jar
4.) Copy of Log4jLoggingNode_v2.0.1.jar to <ACE-INSTALL\server\classes>

Additional notes reg. log4j2 config file (brokerlog.xml): 
Default directory  to loook up the config file seems to be ace-install-dir\server\classes (if not qualified path is given).
The shared-classes folder under mqsi or integration server are NOT checked by default.

**Comment by nieder-github** [comment]
reported as working with v2.0.1
