### ISSUE TITLE
Log4jLoggingNode_v1.2.4.jar with log4j2.x version

### ISSUE THREAD

**Issue by nagkalgur** [ot4i/node-for-log4j#6]
HI,
currently we are with IIB 10 and using Log4jLoggingNode_v1.2.4.jar. we have got a vulnerability from security team to update log4j from 1.2.17 to 2.x

does Log4jLoggingNode_v1.2.4.jar supports log4j2.x version?

**Comment by nieder-github** [comment]
No, v1.2.4 does not support log4j v2.
You have to switch to v2.x of node-for-log4j
That means you have to migrate to a ACE at least v11.0.0.3 or v12.0.3.0.
If you are on z/OS it should also work with IIB v10.0.0.26 or higher.
