### ISSUE TITLE
Question regarding migrating message flow from IIB to App Connect for log4j

### ISSUE THREAD

**Issue by gregoryadri** [ot4i/node-for-log4j#8]
I just migrating my message flow from IIB to App Connect and planning on upgrading log4j from version 1.17 to version 2.x.

If I'm using this latest support pack, do I need to change anything in my code or message flow? Especially on my ESQL code? Or I could use it as usual without any change?

Thank you

**Comment by nieder-github** [comment]
No, you do not need to change  something in your flows.
But see [#3](https://github.com/ot4i/node-for-log4j/issues/3) for a known problem / workaround.

**Comment by nieder-github** [comment]
The log4j config file must be migrated to log4j V2 format.
